{
 "title": "Loki Dashboard",
 "description": "Loki dashboard with quick search and timeline.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "count_over_time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"$namespace\"}[5m])) by (level)"
    }
   ]
  },
  {
   "title": "logs 5min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate( ( {container=\"$namespace\"} |= \"error\" != \"timeout\" [10s] ) )"
    }
   ]
  },
  {
   "title": "Timeline",
   "type": "graph",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\"} |~ \"$search\"[$__interval]))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{container=\"$namespace\"} |= ``"
    }
   ]
  }
 ]
}